---
title: 'Formulae'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

| Purpose       | Formula                                    | R Input                  |
|---------------|:------------------------------------------:|--------------------------|
| Variance      | $s^2 = \frac{\Sigma(X-\bar{X})}{N-1}$      | `var(X)`                 |
| Std Deviation | $s = \sqrt{\frac{\Sigma(X-\bar{X})}{N-1}}$ | `sd(x)`                  |
| z-score       | ${z = \frac{X - \bar{X}}{\sigma}}$         | See below |

| Purpose               | R Input                                                        |
|-----------------------|----------------------------------------------------------------|
| Density               | `dnorm(x, mean = 0, sd = 1, log = FALSE)`                      |
| Distribution Function | `pnorm(q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)` |
| Quantile Function     | `qnorm(p, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)` |
| Random Deviates       | `rnorm(n, mean = 0, sd = 1)`                                   |
      
---

#### Confidence limits on z

$X = \mu \pm 1.96\sigma$

---

#### Chi-Square

Goodness of Fit / 1 Way Classification

$\chi^2 = \sum\frac{(O-E)^2}{E}$

$df = C - 1$

Independence Test / 2 Way Classification

$E_{ij} = \frac{R_{i}C_{j}}{N}$

$df = (R-1)(C-1)$

Sample Size

$\Phi = \sqrt{\frac{\chi^2}{N}}$

---

### Linear Relationships

#### Correlation

$r = \frac{cov_{xy}}{s_{x}s_{y}}$

$df = N-2$

---

#### Covariance

$\frac{(X-\bar{X})(Y-\bar{Y})}{N-1}$

---

#### Significance of r

$t = \frac{r\sqrt{N-2}}{\sqrt{(1-r^2)}}$

---

#### Regression


| Purpose          | Formula                        |
|------------------|--------------------------------|
| General Equation | $\hat{Y} = bX - a$             |
| Slope            | $r = \frac{cov_{xy}}{s_{x}^2}$ |
| Intercept        | $a = \bar{Y} - b\bar{X}$       |

---