---
title: 'Week 8: Analysis of Variance (ANOVA)'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
```

### Introduction {.well}

The differences between the t-test and ANOVA:

| t-test                                                       | Example                              | ANOVA                                            | Example                              |
|--------------------------------------------------------------|--------------------------------------|--------------------------------------------------|--------------------------------------|
| One IV: two categorical levels | campus vs. cloud student             | One IV: three or more categorical levels                     | Young vs. Middle Aged vs. Old        |
| One DV: continuous values                                    | IQ score, exam results, unit results | One DV: Continuous values                        | IQ score, exam results, unit results |
| Examines:<br>&nbsp;- between group variance                              | -                                    | Examines:<br>&nbsp;- between group, and<br>&nbsp;-    within group variance | -                                    |

### Assumptions {.well}

-   Homogeneity of Variance: equal spread of each group around the mean
-   Normality: data is characterised by a normal distribution around the mean
-   Independence of Observations: each score is not related to others. If there is a relationship, scores are not random.
-   If these assumptions are violated, caution is required in interpretation of the results.
-   A larger sample size overcomes the violation of assumptions.

### Sources of error {.well}

-   Individual Differences such as sex, gender, personality, measurement error,
-   Variability within group is called error variance,
-   Differences between groups due to chance or effect of treatment

### F-statistic {.well}

-   Reflects the proportion of variance between groups with the variance within groups.
-   Tells us how many times larger the treatment effect is than the error.
-   Is the difference between groups larger than the error between groups
-   Compare $F_{calc}$ to $F_{crit}$ to determine significance where $\alpha = 0.05$.

If $F_{calc} > F_{crit}$ we can reject $H_0$

\begin{align}
  F &= \frac{variance\ between\ groups}{variance\ within\ groups} \\
  OR \\
  F &= \frac{treatment\ effect\ + difference\ due\ to\ chance}{difference\ due\ to\ chance}
\end{align}

### Logic of ANOVA {.well}

-   Compares whether the difference between means is greater than the difference expected by chance,
-   Denominator referred to as error variance as it represents uncontrollable/random factors,
-   Numerator difference between mean (can also be due to chance or uncontrollable factors),
-   Numerator also contains differences due to treatment,
-   If numerator treatment effect + error is larger than the denominator, there is evidence that treatment is affecting between group (mean) differences.

### Calculation of ANOVA {.well}

Steps:

1.    Sums of Squares (distance of each score from the mean squared)
2.    Degrees of Freedom
3.    Mean Squares
4.    F-value

### Age vs. Happiness notes study from notes {.well}

<table class="table table-hover">
    <tr scope="row">
        <th scope="col"></th>
        <th scope="col">Young People</th>
        <th scope="col">Middle Aged People</th>
        <th scope="col">Old People</th>
    </tr>
    <tr scope="row">
        <td></td>
        <td>6</td>
        <td>7</td>
        <td>8</td>
    </tr>
    <tr scope="row">
        <td></td>
        <td>7</td>
        <td>8</td>
        <td>9</td>
    </tr>
    <tr scope="row">
        <td></td>
        <td>7</td>
        <td>5</td>
        <td>8</td>
    </tr>
    <tr scope="row">
        <td></td>
        <td>6</td>
        <td>7</td>
        <td>8</td>
    </tr>
    <tr scope="row">
        <td></td>
        <td>5</td>
        <td>6</td>
        <td>9</td>
    </tr>
    <tr scope="row">
        <td>Mean</td>
        <td>6.2</td>
        <td>6.6</td>
        <td>8.4</td>
    </tr>
    <tr scope="row">
        <td>Grand Mean</td>
        <td></td>
        <td>7.07</td>
        <td></td>
    </tr>
</table>

#### 1. Sums of Squares (distance of each score from the mean squared)

##### a. Calculate $SS_{treatment}$

>Where:
>
>$\bar{X}_j =$ treatment group mean,
>
>$\bar{X}.. =$ grand mean
>
>$n =$ group sample size
>
>\begin{align}
> SS_{treatment} &= n\Sigma(\bar{X}_{j}-\bar{X}..)^2 \\
> &= 5([6.2-7.07]+[6.6-7.07]+[8.4-7.07]) \\
> &= 5(0.76 + 0.22 + 1.77) \\
> &= 5 \times 2.75 \\
> &= 13.75
>\end{align}

##### b. Calculate $SS_{error}$

>*Difference of each score from the mean of its group:*
>
>Where:
>
>$X_{ij} =$ score of each person in group $j$, and
>
>$\bar{X}_j=$ treatment group mean
>
>\begin{align}
>  SS_{error} &= \Sigma(X_{ij}-\bar{X}_j)^2 \\
> &=[(6-6.2)^2+(7–6.2)^2+(7–6.2)^2+(6–6.2)^2+ \\
>   &(5–6.2)^2+(7–6.6)^2+(8–6.6)^2+(5–6.6)^2+ \\
>   &(7–6.6)^2+(6–6.6)^2+(8–8.4)^2+(9-8.4)^2+ \\
>   &(8–8.4)^2+(8–8.4)^2+(9–8.4)^2] \\
> &=0.04+0.64+0.64+0.04+1.44+0.16+1.96+ \\
>   &2.56+0.16+0.36+0.16+0.36+0.16+0.16+0.36 \\
> &=9.2
>\end{align}


##### c. Calculate $SS_{total}$

>\begin{align}
> SS_{total} &= SS_{treatment} + SS_{error} \\
> &= 13.75+9.2 \\
> &= 22.95
>\end{align}

#### 2. Degrees of Freedom

>Where:
>
>$k =$ number of groups / levels in IV
>
>$n =$ number of people in each group / level
>
>$N=$ total number of participants in study across all groups
>
>\begin{align}
>  df_{treatment} &= k-1 = 3-1 = 2 \\
>  df_{error} &= k(n-1) = 3(5-1) = 12 \\
>  df_{total} &= N-1 = 15-1 = 14 \\
>\end{align}

#### 3. $MS_{treatment}$ and $MS_{error}$

>Dividing the $SS_{treatment}$ and $SS_{error}$ by their respective $df$ values:
>
>\begin{align}
>  MS_{treatment} &= \frac{SS_{treatment}}{df_{treatment}} = \frac{13.75}{2} = 6.875 \\
>  MS_{error} &= \frac{SS_{error}}{df_{error}} = \frac{9.2}{12} = 0.77 \\
>\end{align}

#### 4. Calculate F-value

>\begin{align}
>  F &= \frac{MS_{treatment}}{MS_{error}} = \frac{6.875}{0.77} = 8.93 \\
>\end{align}
>
>-   What does F mean?
>-   Is it significant?

#### 5. Effect Size

>-   Tells us how much the total variability is caused by the difference between treatments
>-   Range from 0 to 1
>-   Represented by eta squared ($\eta^2$)
>
>\begin{align}
>  \eta^2 &= \frac{SS_{treat}}{SS{total}} = \frac{13.75}{22.95} = .60 \\
>\end{align}

#### F-statistic

>-   The F statistic tells us that the effect of the treatment (or the difference between groups) is 8.93 times greater than the error within groups.
>-   You check to see if this is a significant difference using the table at the back of your textbook.
>-   Critical value for F (2, 12) at $\alpha$ = .05 is 3.89.
>-   Since our $F_{calc} > F_{crit}$ we can reject the null hypothesis.

### Reporting {.well}

A one-way ANOVA was conducted to examine whether there was a significant difference in happiness between the young people, middle aged people and old people groups. The analysis found a significant difference between these groups, *F*(2, 12) = 6.875, *p* > .05, $\eta^2_p = .60$.

### One-way ANOVA Summary Formulae {.well}

<table class="table table-hover">
    <tr scope="row">
        <th scope="col">Source</th>
        <th scope="col">df</th>
        <th scope="col">SS</th>
        <th scope="col">MS</th>
        <th scope="col">F</th>
        <th scope="col">p</th>
    </tr>
    <tr scope="row">
        <td><abbr title="Between">Treatment</abbr></td>
        <td><abbr title="k = no. of groups">$k-1$</abbr></td>
        <td><abbr title="n = Group sample size">$n\Sigma(\bar{X}_{j}-\bar{X}..)^2$</abbr></td>
        <td>$\frac{SS_{treatment}}{df_{treatment}}$</td>
        <td>$\frac{MS_{treatment}}{MS_{error}}$</td>
        <td><abbr title="Significance level determined prior to test">.05</abbr></td>
    </tr>
    <tr scope="row">
        <td><abbr title="Within">Error</abbr></td>
        <td><abbr title="k = no. groups, n = Group sample size">$k(n-1)$</abbr></td>
        <td>$\Sigma(X_{ij}-\bar{X}_j)^2$</td>
        <td>$\frac{SS_{error}}{df_{error}}$</td>
        <td></td>
        <td></td>
    </tr>
    <tr scope="row">
        <td>Total</td>
        <td><abbr title="N = Total participants across all groups">$N-1$</abbr></td>
        <td>$SS_{treatment} + SS_{error}$</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr scope="row">
      <td>Effect Size</td>
      <td>$\eta^2$</td>
      <td>$\frac{SS_{treat}}{SS_{total}}$</td>
    </tr>
</table>