---
title: 'Week 10: Factorial ANOVA'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jmv)
```

### Introduction {.well}

-   Used to compare means across multiple groups when there is more than one IV (factor) in the analysis:

    -   IV (categorical)
    -   DV (Continuous)

#### One-Way ANOVA (review)

-   Determining how 'happiness' scores (1 - 10) differ based on age (A one-way comparison as there is only one IV)

    -   One IV: Age (3 levels - young, middle, old)
    -   One DV: Happiness

#### Factorial ANOVA

-   Determine differences in 'happiness' based on age AND gender (a two-way comparison as there are two IVs)

    -   Two IVs:

        -   Age: 3 levels (young, middle, old)
        -   Gender: 2 levels (male, female)

A factorial ANOVA could be used to determine if the effects of age on happiness are the same for males and females.

#### Main & Interaction Effects

With a two-way ANOVA there are three possible effects:

-   Main Effect 1: Overall effect of factor A (ignoring effects of factor B)

-   Main Effect 2: Overall effect of factor B (ignoring effects of factor A)

-   Interaction Effect: where the effect of one factor on the DV is not the same at all levels of the other factor:

    -   Provides information about the relationship between the IVs and DV
    -   Are interpreted best with plots

#### Interaction Example

Two-way ANOVA exploring the effect of temperature on cognitive performance (recall) to determine if the effect is the same for males and females.

-   IV1: Temperature (3 levels: 10$^\circ$, 20$^\circ$, 30$^\circ$)
-   IV2: Gender (2 levels: male and female)
-   DV: Performance (recall)

!Insert graph from handout!

#### Interactions

-   For females, performance improves with temperature
-   For males, temperature has no effect
-   The effect of IV1 (temperature) is not the same at all levels of IV2 (gender)
-   If the plot lines are parallel (do not cross over), there is no interaction

#### Main Effects

!Insert graph 2 from notes

-   A main effect is the effect of IV1 on the DV (overall effect of temperature on cognitive performance), while ignoring the effects of IV2.
-   A main effect is the effect of IV2 on the DV (overall effect of gender on cognitive performance), while ignoring the effects of IV1.
-   Each IV can have a main effect of DV and an individual effect on DV.

### Calculations {.well}

<table class="table table-hover">
    <tr scope="row">
        <th></th>
        <th></th>
        <th scope="col" colspan="2">Stress</th>
    </tr>
    <tr scope="row">
        <td></td>
        <td></td>
        <td>Low</td>
        <td>High</td>
        <td>$Mean_A$</td>
        <td></td>
    </tr>
    <tr scope="row">
        <td rowspan="9">Gender (B)</td>
        <td rowspan="3">Males</td>
        <td>74</td>
        <td>72</td>
        <td></td>
        <td></td>
    </tr>
    <tr scope="row">
        <td>78</td>
        <td>70</td>
        <td></td>
        <td></td>
    </tr>
    <tr scope="row">
        <td>71</td>
        <td>74</td>
        <td></td>
        <td></td>
    </tr>
    <tr scope="row">
        <td>$Mean_{1B}$ </td>
        <td>74.33</td>
        <td>72.00</td>
        <td>73.17</td>
        <td></td>
    </tr>
    <tr scope="row">
        <td rowspan="3">Females</td>
        <td>77</td>
        <td>68</td>
        <td></td>
        <td></td>
    </tr>
    <tr scope="row">
        <td>84</td>
        <td>71</td>
        <td></td>
        <td></td>
    </tr>
    <tr scope="row">
        <td>82</td>
        <td>64</td>
        <td></td>
        <td></td>
    </tr>
    <tr scope="row">
        <td>$Mean_{2B}$</td>
        <td>81.00</td>
        <td>67.67</td>
        <td>74.33</td>
        <td></td>
    </tr>
    <tr scope="row">
        <td>$Mean_B$</td>
        <td>77.67</td>
        <td>69.83</td>
        <td>73.75</td>
        <td><- $\bar{X}..$</td>
    </tr>
</table>

#### Steps

-   $n =$ number of participants in each cell (e.g. males with low anxiety = 3, there are 3 participants in every cell),
-   $a =$ levels of factor A
-   $b =$ levels of factor B

##### Calculate $SS_{total}$

\begin{align}
  SS_{total} &= \Sigma(X-\bar{X}..)^2 \\
  &= (6 – 7.33)^2 + (7 – 7.33)^2 + (9 –7.33)^2 + (8 – 7.33)^2 + (8 – 7.33)^2 + \\
    &   (7 – 7.33)^2 + (4 – 7.33)^2 + (10 – 7.33)^2 + (5 – 7.33)^2 + (9 – 7.33)^2 + \\
    &   (6 – 7.33)^2 + (9 – 7.33)^2 \\
  &=  1.7689 + 0.1089 + 2.7889 + 0.4489 + 0.4489 + 0.1089 + 11.0889 \\
    &   + 7.1289 + 5.4289 + 2.7889 + 1.7689 + 2.7889 \\
  &=  36.667
\end{align}

##### Calculate $SS_A$

\begin{align}
  SS_{A} &= nb\Sigma(\bar{X}_A - \bar{X}..)^2 \\
  &= 3 \times 2[(7.5 - 7.33)^2 + (7.16 - 7.33)^2] \\
  &= 6 \times 0.0578 \\
  &= 0.34 \\
\end{align}

##### Calculate $SS_B$

\begin{align}
  SS_{B} &= na\Sigma(\bar{X}_A - \bar{X}..)^2 \\
  &= 3 \times 2[(6.33 - 7.33)^2 + (8.33 - 7.33)^2] \\
  &= 6 \times 2 \\
  &= 12 \\
\end{align}

##### Calculate $SS_{cells}$

\begin{align}
  SS_{cells} &= n\Sigma(\bar{X}_A - \bar{X}..)^2 \\
  &= 3 \times [(7.67 - 7.33)^2 + (7.33 - 7.33)^2 + (5 - 7.33)^2 + (9.33 - 7.33)^2] \\
  &= 3 \times 9.5445 \\
  &= 28.6335
\end{align}

##### Calculate $SS_{A*B}$

\begin{align}
  SS_{AB} &= SS_{cells} – SS_A – SS_B \\
  &= 28.6335 – 0.34 – 12 \\
  &= 16.3
\end{align}

##### Calculate $SS_{error}$

\begin{align}
  SS_{error} &= SS_{total} – SS_{cells} \\
  &= 36.667 – 28.6335 \\
  &= 8
\end{align}

#### ANOVA Summary Table {.well}

<table class="table table-hover">
  <tr scope="row">
      <th scope="col">df</th>
      <th scope="col"><abbr title="Sum of Squares">SS</abbr></th>
      <th scope="col"><abbr title="Mean of Squares">MS</abbr></th>
      <th scope="col">F</th>
      <th scope="col">p</th>
  </tr>
  <tr scope="row">
    <td>A (gender)</td>
    <td>1</td>
    <td>0.34</td>
    <td>0.34</td>
    <td>0.34</td>
    <td>0.05</td>
  </tr>
  <tr scope="row">
    <td>B (anxiety)</td>
    <td>1</td>
    <td>12</td>
    <td>12</td>
    <td>12</td>
    <td></td>
  </tr>
  <tr scope="row">
    <td>AB (interaction)</td>
    <td>1</td>
    <td>16.3</td>
    <td>16.3</td>
    <td>16.3</td>
    <td></td>
  </tr>
  <tr scope="row">
    <td>Error</td>
    <td>8</td>
    <td>8</td>
    <td>1</td>
    <td></td>
    <td></td>
  </tr>
  <tr scope="row">
    <td>Total</td>
    <td>11</td>
    <td>36.6</td>
  </tr>
</table>

### Reporting {.well}

A two-way ANOVA was conducted to examine the effect of instruction (self-paced or structured) and personality (internal or external) on exam performance. The analysis showed a significant interaction effect, *F*(1, 16) = 5.57, *p* =
.031, $\eta^2_p$ = .26. Internally driven individuals scored higher on the exam when they were provided with a self-paced
learning program (*M* = 82.80, *SD* = 11.30) as opposed to a structured learning program (*M* = 75.20, *SD* = 5.93).
Externally driven individuals scored higher on the exam when they were provided with a structured learning program (*M* = 82.20, *SD* = 6.61) as opposed to a self-paced learning program (*M* = 72.40, *SD* = 8.08).

A two-way ANOVA was conducted to examine the effect of maths anxiety (low or high) and counselling (yes or no) on exam performance. The analysis showed a significant main effect for maths anxiety, *F*(1, 28) = 5.78, *p* = .023, $\eta^2_p$ = .17. On average, students in the low anxiety group (*M* = 81.00, *SD* = 10.30) performed better on the exam than students in the high anxiety group (*M* = 72.50, *SD* = 10.24).

### Two-way ANOVA Summary Table (Formulae) {.well}

<table class="table table-hover">
  <tr scope="row">
      <th scope="col">Source</th>
      <th scope="col">df</th>
      <th scope="col"><abbr title="Sum of Squares">SS</abbr></th>
      <th scope="col"><abbr title="Mean of Squares">MS</abbr></th>
      <th scope="col">F</th>
      <th scope="col">p</th>
  </tr>
  <tr scope="row">
    <td>Factor A</td>
    <td><abbr title="a = # of levels in factor A">$a-1$</abbr></td>
    <td><abbr title="n = # of participants per cell, b = # of levels in B">$nb\Sigma(\bar{X}_A - \bar{X}..)^2$<abbr></abbr></td>
    <td>$\frac{SS_A}{df_A}$</td>
    <td>$\frac{MS_A}{MS_{error}}$</td>
    <td>0.05</td>
  </tr>
  <tr scope="row">
    <td>Factor B</td>
    <td><abbr title="b = # of levels in factor B">$b-1$</abbr></td>
    <td><abbr title="n = # of participants per cell, a = # of levels in A">$na\Sigma(\bar{X}_A - \bar{X}..)^2$</abbr></td>
    <td>$\frac{SS_B}{df_B}$</td>
    <td>$\frac{MS_B}{MS_{error}}$</td>
    <td>&nbsp;</td>
  </tr>
  <tr scope="row">
    <td>A*B (interaction)</td>
    <td><abbr title="(a-1) * (b-1)">$df_A \times df_B$</abbr></td>
    <td>$SS_{cells} – SS_A – SS_B$</td>
    <td>$\frac{SS_{AB}}{df_{AB}}$</td>
    <td>$\frac{MS_{AB}}{MS_{error}}$</td>
    <td>&nbsp;</td>
  </tr>
  <tr scope="row">
    <td>Error</td>
    <td>$df_{total} - df_A - df_B - df_{AB}$</td>
    <td>$SS_{total} – SS_{cells}$</td>
    <td>$\frac{SS_{error}}{df_{error}}$</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr scope="row">
    <td>Total</td>
    <td><abbr title="N = total # of participants">$N-1$</abbr></td>
    <td><abbr title="Sum of squares for each value in the study">$\Sigma(X-\bar{X}..)^2$</abbr></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr scope="row">
    <td colspan="5"><abbr title="omitted from summary like any Sum of Squares value">$SS_{cells} = n\Sigma(\bar{X}_A - \bar{X}..)^2$</abbr></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
